# Generated by Django 4.2.20 on 2025-04-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="contractor",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nhà thầu"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="field",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Lĩnh vực"
            ),
        ),
    ]
