# Generated by Django 3.1.8 on 2025-04-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên gợi nhớ cho camera (ví dụ: Camera Cổng Trước)', max_length=100, unique=True)),
                ('source', models.CharField(help_text='Nguồn video (ID Webcam, đường dẫn file, URL RTSP)', max_length=255, unique=True)),
                ('roi_x', models.IntegerField(blank=True, help_text='Tọa độ X của góc trên bên trái ROI', null=True)),
                ('roi_y', models.IntegerField(blank=True, help_text='Tọa độ Y của góc trên bên trái ROI', null=True)),
                ('roi_w', models.IntegerField(blank=True, help_text='Chiều rộng (Width) của ROI', null=True)),
                ('roi_h', models.IntegerField(blank=True, help_text='Chiều cao (Height) của ROI', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình Camera',
                'verbose_name_plural': 'Các Cấu hình Camera',
                'ordering': ['name'],
            },
        ),
    ]
