# Generated by Django 4.2.20 on 2025-04-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0002_attendancerecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancerecord",
            name="check_in_face",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="check_out_face",
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="check_in_image_url",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="attendance_faces/check_in/",
                verbose_name="Ảnh Check-in",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="check_out_image_url",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="attendance_faces/check_out/",
                verbose_name="Ảnh Check-out",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="company",
            field=models.CharField(
                choices=[("DBplus", "DBplus"), ("DBhomes", "DBhomes")],
                default="DBplus",
                max_length=50,
                verbose_name="Công ty",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="project",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Dự án"
            ),
        ),
        migrations.AlterField(
            model_name="cameraconfig",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="cameraconfig",
            name="source",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
