# Generated by Django 4.2.20 on 2025-04-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0003_remove_attendancerecord_check_in_face_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="employee_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ID nhân viên"
            ),
        ),
    ]
