# Generated by Django 4.2.20 on 2025-04-11 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recognition", "0004_attendancerecord_employee_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("supervisor", "Supervisor"), ("worker", "Worker")],
                        default="worker",
                        max_length=20,
                    ),
                ),
                (
                    "custom_supervisor",
                    models.CharField(
                        blank=True,
                        help_text="Tên giám sát trưởng nếu không có trong hệ thống",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Chọn giám sát trưởng (chỉ áp dụng cho worker)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vai trò người dùng",
                "verbose_name_plural": "Vai trò người dùng",
            },
        ),
    ]
