# Generated by Django 4.2.20 on 2025-04-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0005_userrole"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrole",
            name="supervisor_email",
            field=models.EmailField(
                blank=True,
                help_text="Email của giám sát trưởng",
                max_length=255,
                null=True,
            ),
        ),
    ]
