# Generated by Django 4.2.20 on 2025-04-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0006_userrole_supervisor_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="recognized_by_camera",
            field=models.CharField(
                blank=True,
                help_text="Tên của camera đã thực hiện nhận diện (nếu có)",
                max_length=100,
                null=True,
                verbose_name="Nhận diện bởi Camera",
            ),
        ),
    ]
