# Generated by Django 4.2.20 on 2025-04-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0007_attendancerecord_recognized_by_camera"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancerecord",
            name="recognized_by_camera",
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
    ]
