# Generated by Django 4.2.20 on 2025-04-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0008_remove_attendancerecord_recognized_by_camera_and_more"),
    ]

    operations = []
