# Generated by Django 4.2.20 on 2025-04-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0010_add_recognized_by_camera"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancerecord",
            name="recognized_by_camera",
        ),
    ]
