# Generated by Django 4.2.20 on 2025-04-16 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recognition", "0011_remove_attendancerecord_recognized_by_camera"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledCameraRecognition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Tên lịch trình"),
                ),
                ("start_time", models.TimeField(verbose_name="Thời gian bắt đầu")),
                ("end_time", models.TimeField(verbose_name="Thời gian kết thúc")),
                (
                    "interval_minutes",
                    models.IntegerField(
                        choices=[
                            (15, "15 phút"),
                            (30, "30 phút"),
                            (60, "1 giờ"),
                            (120, "2 giờ"),
                            (180, "3 giờ"),
                            (240, "4 giờ"),
                            (360, "6 giờ"),
                            (720, "12 giờ"),
                        ],
                        default=60,
                        verbose_name="Khoảng thời gian kiểm tra (phút)",
                    ),
                ),
                (
                    "active_days",
                    models.CharField(
                        default="1,2,3,4,5",
                        help_text="Các ngày trong tuần (1-7, 1 là thứ Hai)",
                        max_length=20,
                        verbose_name="Ngày hoạt động",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Đang hoạt động"),
                            ("paused", "Tạm dừng"),
                            ("completed", "Đã hoàn thành"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Lần chạy cuối"
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Lần chạy tiếp theo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="recognition.cameraconfig",
                        verbose_name="Camera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch trình nhận diện tự động",
                "verbose_name_plural": "Các lịch trình nhận diện tự động",
                "ordering": ["camera__name", "start_time"],
            },
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="recognized_by_camera",
            field=models.CharField(
                blank=True,
                help_text="Tên của camera đã thực hiện nhận diện (nếu có)",
                max_length=100,
                null=True,
                verbose_name="Nhận diện bởi Camera",
            ),
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("supervisor", "Supervisor"), ("worker", "Worker")],
                        default="worker",
                        max_length=20,
                    ),
                ),
                (
                    "custom_supervisor",
                    models.CharField(
                        blank=True,
                        help_text="Tên giám sát trưởng nếu không có trong hệ thống",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "supervisor_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email của giám sát trưởng",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Chọn giám sát trưởng (chỉ áp dụng cho worker)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vai trò người dùng",
                "verbose_name_plural": "Vai trò người dùng",
            },
        ),
        migrations.CreateModel(
            name="ScheduledRecognitionLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Thời điểm"),
                ),
                (
                    "success",
                    models.BooleanField(default=False, verbose_name="Thành công"),
                ),
                ("message", models.TextField(verbose_name="Thông báo")),
                (
                    "recognized_users",
                    models.TextField(
                        blank=True,
                        help_text="Danh sách username đã nhận diện, ngăn cách bởi dấu phẩy",
                        null=True,
                        verbose_name="Người dùng đã nhận diện",
                    ),
                ),
                (
                    "attendance_records",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recognition_logs",
                        to="recognition.attendancerecord",
                        verbose_name="Bản ghi chấm công",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="recognition.scheduledcamerarecognition",
                        verbose_name="Lịch trình",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhật ký nhận diện tự động",
                "verbose_name_plural": "Nhật ký nhận diện tự động",
                "ordering": ["-timestamp"],
            },
        ),
    ]
