version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=chamcong123
      - POSTGRES_USER=chamcong
      - POSTGRES_DB=attendance_db
    ports:
      - "5432:5432"
    restart: always
  
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  web:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=0
      - SECRET_KEY=django-insecure-secret-key-please-change-this-in-production
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=attendance_db
      - DB_USER=chamcong
      - DB_PASSWORD=chamcong123
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    # Không map port 8000 ra ngoài, chỉ sử dụng trong mạng nội bộ

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    restart: always
    depends_on:
      - db
      - redis
      - web
    environment:
      - DEBUG=0
      - SECRET_KEY=django-insecure-secret-key-please-change-this-in-production
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=attendance_db
      - DB_USER=chamcong
      - DB_PASSWORD=chamcong123
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - media_volume:/app/media

  nginx:
    image: nginx:latest
    ports:
      - "8078:80"
      - "8079:443"  # Cho HTTPS nếu cần
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - static_volume:/var/www/staticfiles
      - media_volume:/var/www/media
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: