"""
Django settings for attendance_system_facial_recognition project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4!of@+5)(cu6!@c&21m644*%n5)h(9h6shzgg5ka%005e=04qu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'recognition/static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Application definition

INSTALLED_APPS = [
    'users.apps.UsersConfig',
    'recognition.apps.RecognitionConfig',
     
    
    'crispy_forms' ,
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'django_celery_beat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'attendance_system_facial_recognition.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'attendance_system_facial_recognition.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('DB_NAME', os.path.join(BASE_DIR, 'db.sqlite3')),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Thiết lập múi giờ chung cho toàn bộ ứng dụng
TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_L10N = True

# Thiết lập USE_TZ = True để Django sử dụng timezone-aware datetimes
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_URL='login'
LOGOUT_REDIRECT_URL = 'home'


LOGIN_REDIRECT_URL='dashboard'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Đường dẫn gốc cho dữ liệu nhận diện
RECOGNITION_DATA_DIR = os.path.join(BASE_DIR, 'face_recognition_data')

# Đường dẫn file model và dữ liệu
RECOGNITION_PREDICTOR_PATH = os.path.join(RECOGNITION_DATA_DIR, 'shape_predictor_68_face_landmarks.dat')
RECOGNITION_SVC_PATH = os.path.join(RECOGNITION_DATA_DIR, 'svc.sav')
RECOGNITION_CLASSES_PATH = os.path.join(RECOGNITION_DATA_DIR, 'classes.npy')
RECOGNITION_TRAINING_DIR = os.path.join(RECOGNITION_DATA_DIR, 'training_dataset')
RECOGNITION_VISUALIZATION_PATH = os.path.join(BASE_DIR, 'recognition', 'static', 'recognition', 'img', 'training_visualisation.png') # Đường dẫn lưu ảnh visualize

# Thư mục lưu ảnh chấm công (trong MEDIA_ROOT)
RECOGNITION_ATTENDANCE_FACES_DIR = 'attendance_faces' # Đường dẫn tương đối trong MEDIA_ROOT
RECOGNITION_CHECK_IN_SUBDIR = 'check_in'
RECOGNITION_CHECK_OUT_SUBDIR = 'check_out'

# Tham số xử lý ảnh và video
RECOGNITION_FACE_WIDTH = 96        # Chiều rộng mong muốn của khuôn mặt đã căn chỉnh
RECOGNITION_FRAME_WIDTH = 800      # Chiều rộng resize frame video để xử lý/hiển thị
RECOGNITION_FRAME_SKIP = 1       # Xử lý mỗi N frame (giảm từ 3 xuống 2 để thử nghiệm)
RECOGNITION_PREDICTION_THRESHOLD = 0.85# Ngưỡng xác suất để chấp nhận nhận diện (thay đổi từ 0.7 xuống 0.4)

# Tham số thu thập dữ liệu
RECOGNITION_DEFAULT_MAX_SAMPLES = 50 # Số mẫu tối đa cần thu thập

# Tham số ngưỡng nhận diện (số lần liên tiếp)
RECOGNITION_CHECK_IN_THRESHOLD = 5  # Ngưỡng cho check-in
RECOGNITION_CHECK_OUT_THRESHOLD = 5 # Ngưỡng cho check-out


# Số frame bỏ qua khi nhận diện (1 = xử lý mọi frame)
RECOGNIZE_FRAME_SKIP = 1

# Số frame bỏ qua khi thu thập dữ liệu (3 = xử lý frame thứ 3)
COLLECT_FRAME_SKIP = 1

# Cấu hình Celery - Sử dụng biến môi trường nếu có
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE  # Đảm bảo Celery sử dụng cùng timezone với Django

# Cấu hình Channels
ASGI_APPLICATION = 'attendance_system_facial_recognition.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Cấu hình Celery Beat
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'check-continuous-schedules': {
        'task': 'recognition.tasks.schedule_continuous_recognition',
        'schedule': crontab(minute='*/1'),  # Chạy mỗi phút
    },
}

CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(' ')
CSRF_TRUSTED_ORIGINS = [
    'https://attendance.dbplus.com.vn:8086',
    'https://attendance.dbplus.com.vn',
    'http://localhost:8000',
    'http://localhost:8086',
    'http://localhost:8087',
]
